# Generated by Django 2.2.6 on 2019-10-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='writer',
        ),
    ]
